server:
  error:
    include-stacktrace: on_param

spring:
  datasource:
    url: jdbc:h2:./task-manager-db
    username: sa
    password:

  jpa:
    show-sql: true

  h2:
    console:
      enabled: true
      path: /h2console/
      settings:
        web-allow-others: true

logging:
  level:
    root: INFO
    com.rollbar.notifier: DEBUG
    org.springframework.web: DEBUG
    org.springframework.security: INFO
    #org.springframework.web.filter.CommonsRequestLoggingFilter: DEBUG